# Generated by Django 3.2.13 on 2022-05-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20220526_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='longitude',
            new_name='lng',
        ),
    ]
