# Generated by Django 3.2.13 on 2022-05-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20220527_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Office', 'Office')], max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_status',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=200),
        ),
    ]
