# Generated by Django 3.2.13 on 2022-05-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20220530_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='finished',
            new_name='furnished',
        ),
    ]
